In [5]:
print('hello, I am Satvik Tiwari, 12353, This is my assingment')

hello, I am Satvik Tiwari, 12353, This is my assingment


In [3]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 4.0 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.6 MB 3.6 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.6 MB 3.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.6 MB 3.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 3.8 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.6 MB 3.9 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.6 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 4.0 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 4.0 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 4.1 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.6 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 4.3 MB/s eta 0:00:01
   -

In [16]:
#question 1 - 1. Given below is a dictionary having two keys ‘Heights’ and ‘Weights’ and having two lists of heights of
#five Heights and five Weights respectively as values associated with these keys
#Original dictionary of lists:

#CODE

data = {'Heights': [172, 168, 170, 169, 174], 'Weights': [63, 65, 69, 62, 61]}

# Creating the list of dictionaries
list_of_dicts = [{'Heights': data['Heights'][i], 'Weights': data['Weights'][i]} for i in range(len(data['Heights']))]

print(list_of_dicts)


[{'Heights': 172, 'Weights': 63}, {'Heights': 168, 'Weights': 65}, {'Heights': 170, 'Weights': 69}, {'Heights': 169, 'Weights': 62}, {'Heights': 174, 'Weights': 61}]


In [4]:
@question 2 - Write programs in Python using NumPy library to do the following:
a. Compute the mean, standard deviation, and variance of a two dimensional random integer
array along the second axis.
b. Get the indices of the sorted elements of a given array B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and
data type of the array and then reshape it into nx m array, n and m are user inputs given at
the run time.
d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices
of these elements in three separate arrays.

#CODE

import numpy as np

# a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.
array_2d = np.random.randint(0, 100, (5, 10))
mean = np.mean(array_2d, axis=1)
std_dev = np.std(array_2d, axis=1)
variance = np.var(array_2d, axis=1)

# b. Get the indices of the sorted elements of a given array B
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
sorted_indices = np.argsort(B)

# c. Create a 2-dimensional array of size m x n integer elements, print the shape, type and data type, then reshape it into n x m array
m = int(input("Enter number of rows (m): "))
n = int(input("Enter number of columns (n): "))
array_2d_custom = np.random.randint(0, 100, (m, n))
print("Shape:", array_2d_custom.shape)
print("Type:", type(array_2d_custom))
print("Data type:", array_2d_custom.dtype)
reshaped_array = array_2d_custom.reshape(n, m)

# d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.
array_test = np.array([1, 0, np.nan, 3, 4, 0, np.nan])
zero_indices = np.where(array_test == 0)[0]
non_zero_indices = np.where(array_test != 0)[0]
nan_indices = np.where(np.isnan(array_test))[0]

Enter number of rows (m):  3
Enter number of columns (n):  4


Shape: (3, 4)
Type: <class 'numpy.ndarray'>
Data type: int32


In [8]:
#question 3 - Create an array num of size 2 X 3 filled with all zeros then insert [[1,2,3], [4,5,6]] into array. Identify
the shape of the array num.

#CODE


import numpy as np

num = np.zeros((2, 3))
num[:2, :3] = [[1, 2, 3], [4, 5, 6]]
shape = num.shape

In [9]:
#question 4 - Consider a list seq= [1, 2, 0, 4, 6, 5, 2, 1]. Write a code to find the sum of elements of the value till
element 5

#CODE

seq = [1, 2, 0, 4, 6, 5, 2, 1]
total_sum = 0

for num in seq:
    if num == 5:
        break
    total_sum += num

print(total_sum)

13


In [11]:
#question 5 - Write programs in Python using NumPy library to do the following:
a. Create a 5x5 array of
(i) All zeros (ii) all 5s (iii) all zeros but diagonal elements one
b. Consider a list seq= [1, 2, 0, 4, 6, 5, 2, 1]. Write a code to find the sum of elements of
 the values till element 5.

#CODE


import numpy as np

# a. Create a 5x5 array of all zeros
array_zeros = np.zeros((5, 5))
print("5x5 Array of Zeros:\n", array_zeros)

# a. Create a 5x5 array of all 5s
array_fives = np.full((5, 5), 5)
print("5x5 Array of Fives:\n", array_fives)

# a. Create a 5x5 array of all zeros but diagonal elements one
array_diagonal_ones = np.eye(5)
print("5x5 Array with Diagonal Ones:\n", array_diagonal_ones)

# b. Find the sum of elements of the list till element 5
seq = [1, 2, 0, 4, 6, 5, 2, 1]
sum_till_five = sum(seq[:seq.index(5) + 1])
print("Sum of elements till 5:", sum_till_five)

5x5 Array of Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
5x5 Array of Fives:
 [[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
5x5 Array with Diagonal Ones:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Sum of elements till 5: 18


In [12]:
#question 6 - Consider the given arr = [1,2,8,9,3,4,7,5,10,6]. What will be the resulting array if these operations
are performed arr[2:5], arr[-5: -1] and arr[::2].

#CODE

arr = [1, 2, 8, 9, 3, 4, 7, 5, 10, 6]

result_1 = arr[2:5]        # [8, 9, 3]
result_2 = arr[-5:-1]      # [4, 7, 5, 10]
result_3 = arr[::2]        # [1, 8, 3, 7, 10]

print(result_1)
print(result_2)
print(result_3)

[8, 9, 3]
[4, 7, 5, 10]
[1, 8, 3, 7, 10]
